apiVersion: v1
items:
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: guest-console-log
    usage:
      cpu: "0"
      memory: 11888Ki
  - name: compute
    usage:
      cpu: 39223759n
      memory: 1167712Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:26Z"
    labels:
      harvesterhci.io/vmName: 15h08m00s971364-06-12-mgmt
      kubevirt.io: virt-launcher
      kubevirt.io/created-by: c6d8abac-dd08-4383-8f03-096952fb7702
      kubevirt.io/nodeName: hp-69-tink-system
      vm.kubevirt.io/name: 15h08m00s971364-06-12-mgmt
      vmi.kubevirt.io/id: 15h08m00s971364-06-12-mgmt
    name: virt-launcher-15h08m00s971364-06-12-mgmt-hnfp4
    namespace: default
  timestamp: "2026-06-12T23:12:06Z"
  window: 18.23s
kind: List
metadata: {}
