apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-06-12T10:40:00Z"
    name: default
    namespace: local
    resourceVersion: "1645"
    uid: e7edbda2-87e4-4f3a-b3cd-e34f2bdf0da0
kind: List
metadata:
  resourceVersion: "676472"
