apiVersion: v1
items:
- apiVersion: harvesterhci.io/v1beta1
  kind: Addon
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"harvesterhci.io/v1beta1","kind":"Addon","metadata":{"annotations":{},"labels":{"addon.harvesterhci.io/experimental":"true"},"name":"harvester-csi-driver-lvm","namespace":"harvester-system"},"spec":{"chart":"harvester-csi-driver-lvm","enabled":false,"repo":"https://charts.harvesterhci.io","valuesContent":"","version":"1.8.1-rc1"}}
    creationTimestamp: "2026-06-12T23:02:33Z"
    generation: 3
    labels:
      addon.harvesterhci.io/experimental: "true"
    managedFields:
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:addon.harvesterhci.io/experimental: {}
        f:spec:
          .: {}
          f:chart: {}
          f:repo: {}
          f:valuesContent: {}
          f:version: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2026-06-12T23:02:33Z"
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:enabled: {}
      manager: harvester
      operation: Update
      time: "2026-06-12T23:09:11Z"
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:status: {}
      manager: harvester
      operation: Update
      subresource: status
      time: "2026-06-12T23:10:00Z"
    name: harvester-csi-driver-lvm
    namespace: harvester-system
    resourceVersion: "674331"
    uid: a318b456-58dc-4e1f-abf0-7c9e87a165b4
  spec:
    chart: harvester-csi-driver-lvm
    enabled: false
    repo: https://charts.harvesterhci.io
    valuesContent: "null"
    version: 1.8.1-rc1
  status:
    conditions:
    - lastUpdateTime: "2026-06-12T23:10:00Z"
      status: "True"
      type: Completed
    - lastUpdateTime: "2026-06-12T23:10:00Z"
      status: "False"
      type: InProgress
    - lastUpdateTime: "2026-06-12T23:02:33Z"
      status: "False"
      type: OperationFailed
    status: AddonDisabled
- apiVersion: harvesterhci.io/v1beta1
  kind: Addon
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"harvesterhci.io/v1beta1","kind":"Addon","metadata":{"annotations":{},"labels":{"addon.harvesterhci.io/experimental":"true"},"name":"harvester-seeder","namespace":"harvester-system"},"spec":{"chart":"harvester-seeder","enabled":false,"repo":"http://harvester-cluster-repo.cattle-system.svc/charts","valuesContent":"image:\n  tag: v1.8.1-rc1\nfullnameOverride: harvester-seeder\n","version":"1.8.1-rc1"}}
    creationTimestamp: "2026-06-12T10:42:30Z"
    generation: 3
    labels:
      addon.harvesterhci.io/experimental: "true"
    managedFields:
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:addon.harvesterhci.io/experimental: {}
        f:spec:
          .: {}
          f:chart: {}
          f:repo: {}
          f:valuesContent: {}
          f:version: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2026-06-12T10:42:30Z"
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:enabled: {}
      manager: harvester
      operation: Update
      time: "2026-06-12T11:04:43Z"
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:status: {}
      manager: harvester
      operation: Update
      subresource: status
      time: "2026-06-12T11:04:51Z"
    name: harvester-seeder
    namespace: harvester-system
    resourceVersion: "30179"
    uid: 55ad3b87-089c-4d8d-878b-8b81143b0ba2
  spec:
    chart: harvester-seeder
    enabled: false
    repo: http://harvester-cluster-repo.cattle-system.svc/charts
    valuesContent: |
      image:
        tag: v1.8.1-rc1
      fullnameOverride: harvester-seeder
    version: 1.8.1-rc1
  status:
    conditions:
    - lastUpdateTime: "2026-06-12T11:04:51Z"
      status: "True"
      type: Completed
    - lastUpdateTime: "2026-06-12T11:04:51Z"
      status: "False"
      type: InProgress
    - lastUpdateTime: "2026-06-12T10:44:04Z"
      status: "False"
      type: OperationFailed
    status: AddonDisabled
- apiVersion: harvesterhci.io/v1beta1
  kind: Addon
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"harvesterhci.io/v1beta1","kind":"Addon","metadata":{"annotations":{},"labels":{"addon.harvesterhci.io/experimental":"true"},"name":"harvester-vm-dhcp-controller","namespace":"harvester-system"},"spec":{"chart":"harvester-vm-dhcp-controller","enabled":false,"repo":"https://charts.harvesterhci.io","valuesContent":"","version":"1.8.1-dev.0"}}
    creationTimestamp: "2026-06-12T15:27:57Z"
    generation: 3
    labels:
      addon.harvesterhci.io/experimental: "true"
    managedFields:
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:addon.harvesterhci.io/experimental: {}
        f:spec:
          .: {}
          f:chart: {}
          f:repo: {}
          f:valuesContent: {}
          f:version: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2026-06-12T15:27:57Z"
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:enabled: {}
      manager: harvester
      operation: Update
      time: "2026-06-12T15:30:19Z"
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:status: {}
      manager: harvester
      operation: Update
      subresource: status
      time: "2026-06-12T15:30:27Z"
    name: harvester-vm-dhcp-controller
    namespace: harvester-system
    resourceVersion: "311582"
    uid: dcf11f52-54ba-454c-b082-6c42989c17c5
  spec:
    chart: harvester-vm-dhcp-controller
    enabled: false
    repo: https://charts.harvesterhci.io
    valuesContent: "null"
    version: 1.8.1-dev.0
  status:
    conditions:
    - lastUpdateTime: "2026-06-12T15:30:27Z"
      status: "True"
      type: Completed
    - lastUpdateTime: "2026-06-12T15:30:27Z"
      status: "False"
      type: InProgress
    - lastUpdateTime: "2026-06-12T15:27:57Z"
      status: "False"
      type: OperationFailed
    status: AddonDisabled
- apiVersion: harvesterhci.io/v1beta1
  kind: Addon
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"harvesterhci.io/v1beta1","kind":"Addon","metadata":{"annotations":{},"name":"nvidia-driver-toolkit","namespace":"harvester-system"},"spec":{"chart":"nvidia-driver-runtime","enabled":false,"repo":"http://harvester-cluster-repo.cattle-system.svc/charts","valuesContent":"image:\n  tag: v1.8-20260605\n  repo: rancher/harvester-nvidia-driver-toolkit\ndriverLocation:  \"HTTPENDPOINT/NVIDIA-Linux-x86_64-vgpu-kvm.run\"\nfullnameOverride: nvidia-driver-runtime\n","version":"1.8.1-rc1"}}
    creationTimestamp: "2026-06-12T10:42:30Z"
    generation: 3
    managedFields:
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          .: {}
          f:chart: {}
          f:repo: {}
          f:valuesContent: {}
          f:version: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2026-06-12T10:42:30Z"
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:enabled: {}
      manager: harvester
      operation: Update
      time: "2026-06-12T11:04:52Z"
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:status: {}
      manager: harvester
      operation: Update
      subresource: status
      time: "2026-06-12T11:05:01Z"
    name: nvidia-driver-toolkit
    namespace: harvester-system
    resourceVersion: "30478"
    uid: e6ec9a7b-02ee-4ca4-a814-ba78529d3644
  spec:
    chart: nvidia-driver-runtime
    enabled: false
    repo: http://harvester-cluster-repo.cattle-system.svc/charts
    valuesContent: |
      image:
        tag: v1.8-20260605
        repo: rancher/harvester-nvidia-driver-toolkit
      driverLocation:  "HTTPENDPOINT/NVIDIA-Linux-x86_64-vgpu-kvm.run"
      fullnameOverride: nvidia-driver-runtime
    version: 1.8.1-rc1
  status:
    conditions:
    - lastUpdateTime: "2026-06-12T11:05:01Z"
      status: "True"
      type: Completed
    - lastUpdateTime: "2026-06-12T11:05:01Z"
      status: "False"
      type: InProgress
    - lastUpdateTime: "2026-06-12T10:44:04Z"
      status: "False"
      type: OperationFailed
    status: AddonDisabled
- apiVersion: harvesterhci.io/v1beta1
  kind: Addon
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"harvesterhci.io/v1beta1","kind":"Addon","metadata":{"annotations":{},"name":"pcidevices-controller","namespace":"harvester-system"},"spec":{"chart":"harvester-pcidevices-controller","enabled":false,"repo":"http://harvester-cluster-repo.cattle-system.svc/charts","valuesContent":"image:\n  tag: v1.8.1-rc1\nfullnameOverride: harvester-pcidevices-controller\n","version":"1.8.1-rc1"}}
    creationTimestamp: "2026-06-12T10:42:30Z"
    generation: 3
    managedFields:
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          .: {}
          f:chart: {}
          f:repo: {}
          f:valuesContent: {}
          f:version: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2026-06-12T10:42:30Z"
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:enabled: {}
      manager: harvester
      operation: Update
      time: "2026-06-12T11:05:02Z"
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:status: {}
      manager: harvester
      operation: Update
      subresource: status
      time: "2026-06-12T11:05:10Z"
    name: pcidevices-controller
    namespace: harvester-system
    resourceVersion: "30735"
    uid: 954829b7-e9b8-49a5-9e7f-e6df070ebae8
  spec:
    chart: harvester-pcidevices-controller
    enabled: false
    repo: http://harvester-cluster-repo.cattle-system.svc/charts
    valuesContent: |
      image:
        tag: v1.8.1-rc1
      fullnameOverride: harvester-pcidevices-controller
    version: 1.8.1-rc1
  status:
    conditions:
    - lastUpdateTime: "2026-06-12T11:05:10Z"
      status: "True"
      type: Completed
    - lastUpdateTime: "2026-06-12T11:05:10Z"
      status: "False"
      type: InProgress
    - lastUpdateTime: "2026-06-12T10:44:04Z"
      status: "False"
      type: OperationFailed
    status: AddonDisabled
- apiVersion: harvesterhci.io/v1beta1
  kind: Addon
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"harvesterhci.io/v1beta1","kind":"Addon","metadata":{"annotations":{},"name":"vm-import-controller","namespace":"harvester-system"},"spec":{"chart":"harvester-vm-import-controller","enabled":false,"repo":"http://harvester-cluster-repo.cattle-system.svc/charts","valuesContent":"image:\n  tag: v1.8.1-rc1\nfullnameOverride: harvester-vm-import-controller\n","version":"1.8.1-rc1"}}
    creationTimestamp: "2026-06-12T10:42:30Z"
    generation: 3
    managedFields:
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          .: {}
          f:chart: {}
          f:repo: {}
          f:valuesContent: {}
          f:version: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2026-06-12T10:42:30Z"
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:enabled: {}
      manager: harvester
      operation: Update
      time: "2026-06-12T11:05:11Z"
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:status: {}
      manager: harvester
      operation: Update
      subresource: status
      time: "2026-06-12T11:05:19Z"
    name: vm-import-controller
    namespace: harvester-system
    resourceVersion: "30974"
    uid: db1a7fe9-bef3-42f5-b56c-bce1f18035e2
  spec:
    chart: harvester-vm-import-controller
    enabled: false
    repo: http://harvester-cluster-repo.cattle-system.svc/charts
    valuesContent: |
      image:
        tag: v1.8.1-rc1
      fullnameOverride: harvester-vm-import-controller
    version: 1.8.1-rc1
  status:
    conditions:
    - lastUpdateTime: "2026-06-12T11:05:19Z"
      status: "True"
      type: Completed
    - lastUpdateTime: "2026-06-12T11:05:19Z"
      status: "False"
      type: InProgress
    - lastUpdateTime: "2026-06-12T10:44:04Z"
      status: "False"
      type: OperationFailed
    status: AddonDisabled
kind: List
metadata:
  continue: "null"
  resourceVersion: "676448"
