apiVersion: v1
items:
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-06-12T10:42:08Z"
    name: default
    namespace: cattle-monitoring-system
    resourceVersion: "26575"
    uid: 63cc0693-e303-43aa-93fb-3760ee878b81
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-monitoring-crd
      meta.helm.sh/release-namespace: cattle-monitoring-system
      objectset.rio.cattle.io/id: default-mcc-rancher-monitoring-crd-cattle-fleet-local-system
    creationTimestamp: "2026-06-12T10:42:17Z"
    labels:
      app: rancher-monitoring-crd-manager
      app.kubernetes.io/managed-by: Helm
      objectset.rio.cattle.io/hash: 2da503261617e9ea2da822d2da7cdcfccad847a9
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            f:app: {}
            f:app.kubernetes.io/managed-by: {}
            f:objectset.rio.cattle.io/hash: {}
      manager: fleetagent
      operation: Apply
      time: "2026-06-12T10:42:17Z"
    name: rancher-monitoring-crd-manager
    namespace: cattle-monitoring-system
    resourceVersion: "3442"
    uid: 505b95c0-f04a-40d8-9721-7100c5a204b0
kind: List
metadata:
  resourceVersion: "676419"
