apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      kubevirt.io/generation: "5"
      kubevirt.io/install-strategy-identifier: b357896524d764ec4a976e713d49941f84dcf0e8
      kubevirt.io/install-strategy-registry: registry.suse.com/suse/sles/15.7
      kubevirt.io/install-strategy-version: 1.7.0-150700.3.21.1
    creationTimestamp: "2026-06-12T10:43:23Z"
    generation: 1
    labels:
      app.kubernetes.io/component: kubevirt
      app.kubernetes.io/managed-by: virt-operator
      k8s-app: kubevirt
      openshift.io/cluster-monitoring: "null"
      prometheus.kubevirt.io: "true"
    managedFields:
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubevirt.io/generation: {}
            f:kubevirt.io/install-strategy-identifier: {}
            f:kubevirt.io/install-strategy-registry: {}
            f:kubevirt.io/install-strategy-version: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/managed-by: {}
            f:k8s-app: {}
            f:openshift.io/cluster-monitoring: {}
            f:prometheus.kubevirt.io: {}
        f:spec:
          .: {}
          f:endpoints: {}
          f:namespaceSelector:
            .: {}
            f:matchNames: {}
          f:selector: {}
      manager: virt-operator
      operation: Update
      time: "2026-06-12T13:10:56Z"
    name: prometheus-kubevirt-rules
    namespace: cattle-monitoring-system
    resourceVersion: "154706"
    uid: 2d053ca2-3714-40d0-b2d5-4920a5d9da31
  spec:
    endpoints:
    - honorLabels: true
      port: metrics
      scheme: https
      tlsConfig:
        ca: {}
        cert: {}
        insecureSkipVerify: true
    namespaceSelector:
      matchNames:
      - harvester-system
    selector:
      matchLabels:
        prometheus.kubevirt.io: "true"
kind: List
metadata:
  continue: "null"
  resourceVersion: "676422"
