apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-06-12T10:40:31Z"
    name: default
    namespace: cattle-fleet-system
    resourceVersion: "1867"
    uid: 24ba924e-d172-4ba1-ad8c-e2e8bc37c86e
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: fleet
      meta.helm.sh/release-namespace: cattle-fleet-system
    creationTimestamp: "2026-06-12T10:40:38Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
      manager: helm
      operation: Update
      time: "2026-06-12T10:40:38Z"
    name: fleet-controller
    namespace: cattle-fleet-system
    resourceVersion: "1950"
    uid: fd54284e-8e91-4aec-a09d-65a5810e5842
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: fleet
      meta.helm.sh/release-namespace: cattle-fleet-system
    creationTimestamp: "2026-06-12T10:40:38Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
      manager: helm
      operation: Update
      time: "2026-06-12T10:40:38Z"
    name: gitjob
    namespace: cattle-fleet-system
    resourceVersion: "1951"
    uid: e8a9cc7a-0bfa-40e4-8dcd-5c28cc530552
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: fleet
      meta.helm.sh/release-namespace: cattle-fleet-system
    creationTimestamp: "2026-06-12T10:40:38Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
      manager: helm
      operation: Update
      time: "2026-06-12T10:40:38Z"
    name: helmops
    namespace: cattle-fleet-system
    resourceVersion: "1949"
    uid: 703d0ddf-6a22-4f2d-b14a-7b553f868d1d
kind: List
metadata:
  resourceVersion: "676388"
