apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-06-12T10:40:42Z"
    name: default
    namespace: cattle-fleet-clusters-system
    resourceVersion: "2078"
    uid: 040429ed-ca8c-4686-af92-fb0485b60b68
kind: List
metadata:
  resourceVersion: "676397"
