
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  creationTimestamp: null
  name: imgencrypters.harvesterhci.io
spec:
  group: harvesterhci.io
  names:
    kind: ImgEncrypter
    listKind: ImgEncrypterList
    plural: imgencrypters
    singular: imgencrypter
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.stage
      name: STAGE
      type: integer
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              displayName:
                type: string
              srcImgNames:
                type: string
              srcImgNamespace:
                type: string
            required:
            - displayName
            - srcImgNames
            - srcImgNamespace
            type: object
          status:
            properties:
              stage:
                format: int64
                type: integer
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
