apiVersion: v1
items:
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: fleet-agent
    usage:
      cpu: 1021044n
      memory: 169324Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:30Z"
    labels:
      app: fleet-agent
      pod-template-hash: 598d897c9b
    name: fleet-agent-598d897c9b-nmhq2
    namespace: cattle-fleet-local-system
  timestamp: "2026-06-12T23:12:09Z"
  window: 12.45s
kind: List
metadata: {}
