apiVersion: v1
items:
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4xTXW/bOgz9KwUfL5zE8VccvwVBcC/Qj9u16YBhKAqaYhKltmRIcrCu8H8fZHtY1g3r4AdLFA95zqH0CjU7FOgQildApbRDJ7WyfqvLI5Oz7KZG6imhcxVPpZ5JAQWYZ44mNdJBKp6QVju5n1DFqNoGugAqLLn6Y5UD2gMUIMRSlLQTC4rzPE9FHPIiRyqzFNOc02UWZUmYh5EvqrDmN61/7jwho9VRlzDk2gbJA3YVs5tUmrDyZWzD5JkddbnluqnQsd+eOXGWVCI9693uStbSQTEPA3DvYkgrh1KxsVB8fgU0e7+A2YGrhs1sJDu1B3gMgHRdoxJ9QinVbIiyOvXYUfJ6td1ebZ7uN3cfN3fQBW8P1qun9X+b9eX9wzUEcMKq7XWLZbTLllGM83AXCxRpxlm6FGES4SJeZDSnMOM5YZZgzlwyLebZQuQ0z9ME4+Q3jbb/X25uzlokd/ZohAlP8SfxdfthAd1jALLGfT8oVHRgMxv/E9yzcsUpms6TaQR/M89GCwjAsNWtIbajzUytke5lrZXjL847blq1sv8a3TZQZGkaJ8EQerBsxkgXwElXbc3XulVumEztl7fo/EUcp/OD1khlAEH36JUZtg6Nu9WVpBco4IZPPcSyOUniFZGvePOuLovwnc7AZDi/xsared8XS0Y27uxN/EK267xTdGDRVj4hvQgv/vFf/wIcurZ3s/sWAAD//86X4gQCBAAA
      objectset.rio.cattle.io/id: rke2-machine-config-cleanup
    creationTimestamp: "2026-06-12T10:42:20Z"
    generation: 2
    labels:
      objectset.rio.cattle.io/hash: dd9dbcfd7c38885d30e78acb65a58e5962640802
    managedFields:
    - apiVersion: batch/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
        f:spec:
          f:concurrencyPolicy: {}
          f:failedJobsHistoryLimit: {}
          f:jobTemplate:
            f:spec:
              f:backoffLimit: {}
              f:template:
                f:spec:
                  f:containers:
                    k:{"name":"rke2-machineconfig-cleanup-pod"}:
                      .: {}
                      f:args: {}
                      f:command: {}
                      f:env:
                        .: {}
                        k:{"name":"CATTLE_CA_CHECKSUM"}:
                          .: {}
                          f:name: {}
                          f:value: {}
                        k:{"name":"CATTLE_SERVER"}:
                          .: {}
                          f:name: {}
                        k:{"name":"CATTLE_TOKEN"}:
                          .: {}
                          f:name: {}
                          f:value: {}
                      f:image: {}
                      f:imagePullPolicy: {}
                      f:name: {}
                      f:resources: {}
                      f:securityContext:
                        .: {}
                        f:runAsGroup: {}
                        f:runAsUser: {}
                      f:terminationMessagePath: {}
                      f:terminationMessagePolicy: {}
                      f:volumeMounts:
                        .: {}
                        k:{"mountPath":"/helper"}:
                          .: {}
                          f:mountPath: {}
                          f:name: {}
                  f:dnsPolicy: {}
                  f:restartPolicy: {}
                  f:schedulerName: {}
                  f:securityContext: {}
                  f:serviceAccount: {}
                  f:serviceAccountName: {}
                  f:terminationGracePeriodSeconds: {}
                  f:volumes:
                    .: {}
                    k:{"name":"config-volume"}:
                      .: {}
                      f:configMap:
                        .: {}
                        f:defaultMode: {}
                        f:name: {}
                      f:name: {}
          f:schedule: {}
          f:successfulJobsHistoryLimit: {}
          f:suspend: {}
      manager: rancher
      operation: Update
      time: "2026-06-12T10:45:19Z"
    name: rke2-machineconfig-cleanup-cronjob
    namespace: fleet-local
    resourceVersion: "8769"
    uid: 047a57f1-6ee6-43ca-940b-6a1a02933365
  spec:
    concurrencyPolicy: Allow
    failedJobsHistoryLimit: 1
    jobTemplate:
      metadata: {}
      spec:
        backoffLimit: 10
        template:
          metadata: {}
          spec:
            containers:
            - args:
              - /helper/cleanup.sh
              command:
              - /bin/sh
              env:
              - name: CATTLE_SERVER
              - name: CATTLE_CA_CHECKSUM
                value: fd92f6923a10f3dad56e659d042a7376c1c06e1ca64a8eebec7167d8c1854a34
              - name: CATTLE_TOKEN
                value: 4Rsjrdr0v3YdzTQ7
              image: rancher/rancher-agent:v2.14.2
              imagePullPolicy: IfNotPresent
              name: rke2-machineconfig-cleanup-pod
              resources: {}
              securityContext:
                runAsGroup: 65534
                runAsUser: 65534
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
              - mountPath: /helper
                name: config-volume
            dnsPolicy: ClusterFirst
            restartPolicy: Never
            schedulerName: default-scheduler
            securityContext: {}
            serviceAccount: rke2-machineconfig-cleanup-sa
            serviceAccountName: rke2-machineconfig-cleanup-sa
            terminationGracePeriodSeconds: 30
            volumes:
            - configMap:
                defaultMode: 420
                name: rke2-machineconfig-cleanup-script
              name: config-volume
    schedule: 5 0 * * *
    successfulJobsHistoryLimit: 3
    suspend: false
  status: {}
kind: List
metadata:
  resourceVersion: "676422"
