apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-06-12T10:42:08Z"
    name: default
    namespace: cattle-logging-system
    resourceVersion: "2937"
    uid: 98f50383-eb79-46f5-9256-6ac331c73feb
kind: List
metadata:
  resourceVersion: "676499"
