apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-06-12T10:39:05Z"
    name: default
    namespace: default
    resourceVersion: "509"
    uid: d2925884-5d81-48d2-8427-1cb3f95d0c11
kind: List
metadata:
  resourceVersion: "676315"
