apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-06-12T10:39:05Z"
    name: default
    namespace: cattle-system
    resourceVersion: "508"
    uid: 7637bad9-b923-46d4-8fad-4ebee2595658
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yRsU7DMBCGXwXdHJekTtIkEgMSC2IAgcSCGC72tTV17Mq+BqEq745MBwqiqKOl/z9/990eBmLUyAjdHtA5z8jGu5ievn8jxZF4FoyfKWS2NDP+0mjoALcmUhiNIshOJv27oyBW4wY6GNDhigZyfBQYZXZxZ5y+un64fTpznMOBoIM1hpEiUzirELeoUgumDCz2ZP/dcI1xDR0UZV2oOq+KRqmiamRbSJ33jW4a6qWUWJaYtzVWaehvKoFbI74NHTMc/hHxIzINiT5RPtKSAjlFEbqXfdL7TCEa706rgwx669XmPvVvyBJ/xZdoI2WgvOPgraUAHYcdZbAxLl3uh+o/ZO4O98112WisRElqLkpFC9HKOYqF7NsSl/WibjVMr9P0GQAA//8u/ypRQwIAAA
      objectset.rio.cattle.io/id: apiservice
      objectset.rio.cattle.io/owner-gvk: management.cattle.io/v3, Kind=APIService
      objectset.rio.cattle.io/owner-name: harvester
      objectset.rio.cattle.io/owner-namespace: "null"
      rancher.io/service-account.secret-ref: cattle-system/harvester-api-service-token-r4jrt
    creationTimestamp: "2026-06-12T10:42:47Z"
    labels:
      objectset.rio.cattle.io/hash: 1461c60518cc1583913d0b8d88eb333a44a096a5
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
            f:rancher.io/service-account.secret-ref: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"a0d48da5-4ec2-4ce7-932a-73b94af6769d"}: {}
      manager: rancher
      operation: Update
      time: "2026-06-12T10:42:48Z"
    name: harvester-api-service
    namespace: cattle-system
    ownerReferences:
    - apiVersion: management.cattle.io/v3
      blockOwnerDeletion: false
      controller: true
      kind: APIService
      name: harvester
      uid: a0d48da5-4ec2-4ce7-932a-73b94af6769d
    resourceVersion: "5181"
    uid: debc4379-1e7a-4d8f-8cb0-ce54c9f7a6a9
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher
      meta.helm.sh/release-namespace: cattle-system
      rancher.io/service-account.secret-ref: cattle-system/rancher-token-r7qg4
    creationTimestamp: "2026-06-12T10:39:02Z"
    labels:
      app: rancher
      app.kubernetes.io/managed-by: Helm
      chart: rancher-2.14.2
      heritage: Helm
      release: rancher
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/managed-by: {}
            f:chart: {}
            f:heritage: {}
            f:release: {}
      manager: helm
      operation: Update
      time: "2026-06-12T10:39:02Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:rancher.io/service-account.secret-ref: {}
      manager: rancher
      operation: Update
      time: "2026-06-12T10:39:48Z"
    name: rancher
    namespace: cattle-system
    resourceVersion: "1217"
    uid: 35ff85a5-a615-4874-9879-9e81af790782
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-webhook
      meta.helm.sh/release-namespace: cattle-system
    creationTimestamp: "2026-06-12T10:41:46Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
      manager: helm
      operation: Update
      time: "2026-06-12T10:41:46Z"
    name: rancher-webhook
    namespace: cattle-system
    resourceVersion: "2558"
    uid: 40f33cad-3f3f-4d89-b7f1-b009530e7231
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      cattle.io/description: SA which can be impersonated to bypass rancher-webhook
        validation
      meta.helm.sh/release-name: rancher-webhook
      meta.helm.sh/release-namespace: cattle-system
    creationTimestamp: "2026-06-12T10:41:46Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:cattle.io/description: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
      manager: helm
      operation: Update
      time: "2026-06-12T10:41:46Z"
    name: rancher-webhook-sudo
    namespace: cattle-system
    resourceVersion: "2557"
    uid: b10e0629-9135-45da-8b40-35a33572cbb2
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yOS46DMBBE79LrgTFfDb5Nud0Cj7CNcGcRIe4eIbLIKstSfV4dFEXhoSB7EFLKCg05lUtm9y+sRbTeQ64ZqqvUIf8GT5YiEmbxVXkWlVhhlqR0/tAKJ+vX+oKykKVxYjc0Zmx6dL13hhmQqTdsRmkNN38td5jccI0mRCFLn6zqsc07vOx022UDX5mb875F5/kKAAD//+eYuJviAAAA
      objectset.rio.cattle.io/id: managed-system-agent
    creationTimestamp: "2026-06-12T10:45:22Z"
    labels:
      objectset.rio.cattle.io/hash: 69cb510614a34db0ccaae940c06e20c182c3a9b5
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
      manager: rancher
      operation: Update
      time: "2026-06-12T10:45:22Z"
    name: system-agent-upgrader
    namespace: cattle-system
    resourceVersion: "8902"
    uid: 6976e5d0-451a-4dea-a800-81195dc94410
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: mcc-local-managed-system-upgrade-controller
      meta.helm.sh/release-namespace: cattle-system
    creationTimestamp: "2026-06-12T10:42:21Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
      manager: helm
      operation: Update
      time: "2026-06-12T10:42:21Z"
    name: system-upgrade-controller
    namespace: cattle-system
    resourceVersion: "3810"
    uid: 3d339dff-934a-4429-a7b3-f3b100ccfbb7
kind: List
metadata:
  resourceVersion: "676344"
