apiVersion: v1
items:
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: fleet-agent-local
      meta.helm.sh/release-namespace: cattle-fleet-local-system
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yOTW7rMAwG78J15JenxH/a9QztBSjpU6NWFgOLLlAEuXtheJ/lDInB9yDeVBbZqr5j/ckBbyHs9CHfqOQSl4YTLVCOrEzuQVyrKGuW2nYU/4WgDdqtWbrAqgVdln85kqNUADX8iarGi2jTle/meDLHsUjgYtpvUyz0PFFhj/KyfON2I0eXwZ7tJY29xZj+z9McJz/0Fmc7+2jD0E+MMVyve7TyAnIUkXgrSododw67fTHn+RcAAP//F9FSKSABAAA
      objectset.rio.cattle.io/id: fleet-agent-bootstrap-cattle-fleet-local-system
    creationTimestamp: "2026-06-12T10:42:09Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      objectset.rio.cattle.io/hash: 362023f752e7f1989d8b652e029bd2c658ae7c44
    name: default
    namespace: cattle-fleet-local-system
    resourceVersion: "3416"
    uid: 5617bb0e-7aa8-4ca1-993c-3c352fb3bfc8
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: fleet-agent-local
      meta.helm.sh/release-namespace: cattle-fleet-local-system
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yOPQ6DMAxG7+K5oTT8cxsnMSVViBH2UiHuXiGmLoz2+/T0dlhIMaAijDtgzqyokbOcJ7sPeRXSYotceFRNVER+xgAjTIlIDb4pq3HMKrrhaq6RuWBij8nIV5QWOB6Q0FG6Nc8oM4xQtba01dQ1lrrpNfRD6F3bWCrt4IL1bdMjdb6uT2nGhf5z4HrKiv4kN0nHLwAA//+nZcfN/wAAAA
      objectset.rio.cattle.io/id: fleet-agent-bootstrap-cattle-fleet-local-system
    creationTimestamp: "2026-06-12T10:42:09Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      objectset.rio.cattle.io/hash: 362023f752e7f1989d8b652e029bd2c658ae7c44
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
      manager: fleetcontroller
      operation: Update
      time: "2026-06-12T10:42:09Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            f:app.kubernetes.io/managed-by: {}
      manager: fleetagent
      operation: Update
      time: "2026-06-12T10:42:16Z"
    name: fleet-agent
    namespace: cattle-fleet-local-system
    resourceVersion: "3415"
    uid: 51eac496-1472-44a4-a326-dffeaf94b892
kind: List
metadata:
  resourceVersion: "676368"
