apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      meta.helm.sh/release-name: harvester-csi-driver-lvm
      meta.helm.sh/release-namespace: harvester-system
    creationTimestamp: "2026-06-12T23:03:19Z"
    generation: 1
    labels:
      app.kubernetes.io/component: storage
      app.kubernetes.io/instance: harvester-csi-driver-lvm
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: harvester-csi-driver-lvm-controller
      app.kubernetes.io/version: v1.8.1-rc1
      helm.sh/chart: harvester-csi-driver-lvm-1.8.1-rc1
    managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:spec:
          f:persistentVolumeClaimRetentionPolicy:
            .: {}
            f:whenDeleted: {}
            f:whenScaled: {}
          f:podManagementPolicy: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:serviceName: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app.kubernetes.io/component: {}
                f:app.kubernetes.io/instance: {}
                f:app.kubernetes.io/managed-by: {}
                f:app.kubernetes.io/name: {}
                f:app.kubernetes.io/version: {}
                f:helm.sh/chart: {}
            f:spec:
              f:affinity:
                .: {}
                f:podAffinity:
                  .: {}
                  f:requiredDuringSchedulingIgnoredDuringExecution: {}
              f:containers:
                k:{"name":"csi-attacher"}:
                  .: {}
                  f:args: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:privileged: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/csi"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                k:{"name":"csi-provisioner"}:
                  .: {}
                  f:args: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:privileged: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/csi"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                k:{"name":"csi-resizer"}:
                  .: {}
                  f:args: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:privileged: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/csi"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                k:{"name":"csi-snapshotter"}:
                  .: {}
                  f:args: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:privileged: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/csi"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:serviceAccount: {}
              f:serviceAccountName: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"socket-dir"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
          f:updateStrategy:
            f:rollingUpdate:
              .: {}
              f:partition: {}
            f:type: {}
      manager: helm
      operation: Update
      time: "2026-06-12T23:03:19Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:availableReplicas: {}
          f:collisionCount: {}
          f:currentReplicas: {}
          f:currentRevision: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updateRevision: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2026-06-12T23:03:31Z"
    name: harvester-csi-driver-lvm-controller
    namespace: harvester-system
    resourceVersion: "669086"
    uid: 10170070-70fc-43ca-aa09-ced2d13e6b75
  spec:
    persistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: harvester-csi-driver-lvm
        app.kubernetes.io/name: harvester-csi-driver-lvm-controller
    serviceName: harvester-csi-driver-lvm-controller
    template:
      metadata:
        labels:
          app.kubernetes.io/component: storage
          app.kubernetes.io/instance: harvester-csi-driver-lvm
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: harvester-csi-driver-lvm-controller
          app.kubernetes.io/version: v1.8.1-rc1
          helm.sh/chart: harvester-csi-driver-lvm-1.8.1-rc1
      spec:
        affinity:
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - harvester-csi-driver-lvm
              topologyKey: kubernetes.io/hostname
        containers:
        - args:
          - --v=5
          - --csi-address=/csi/csi.sock
          image: registry.k8s.io/sig-storage/csi-attacher:v4.4.2
          imagePullPolicy: IfNotPresent
          name: csi-attacher
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
        - args:
          - -v=5
          - --csi-address=/csi/csi.sock
          - --feature-gates=Topology=true
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.2
          imagePullPolicy: IfNotPresent
          name: csi-provisioner
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
        - args:
          - -v=5
          - -csi-address=/csi/csi.sock
          image: registry.k8s.io/sig-storage/csi-resizer:v1.9.2
          imagePullPolicy: IfNotPresent
          name: csi-resizer
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
        - args:
          - -v=5
          - -csi-address=/csi/csi.sock
          image: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.4
          imagePullPolicy: IfNotPresent
          name: csi-snapshotter
          resources: {}
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: harvester-csi-driver-lvm
        serviceAccountName: harvester-csi-driver-lvm
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/lvm.driver.harvesterhci.io
            type: DirectoryOrCreate
          name: socket-dir
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
  status:
    availableReplicas: 1
    collisionCount: 0
    currentReplicas: 1
    currentRevision: harvester-csi-driver-lvm-controller-6b56dc9bc9
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updateRevision: harvester-csi-driver-lvm-controller-6b56dc9bc9
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: "676447"
