apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.42
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: hp-117-tink-system
    targetRef:
      kind: Pod
      name: longhorn-manager-bvg2r
      namespace: longhorn-system
      uid: f69f3692-00cb-4087-b546-1f5985ef9619
  - addresses:
    - 10.52.1.5
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: hp-150-tink-system
    targetRef:
      kind: Pod
      name: longhorn-manager-l4qr4
      namespace: longhorn-system
      uid: 777ca1c3-22e8-4721-b43d-188ab4933a86
  - addresses:
    - 10.52.2.8
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: hp-69-tink-system
    targetRef:
      kind: Pod
      name: longhorn-manager-prlhd
      namespace: longhorn-system
      uid: b85fcfb0-d2a1-4ac3-b81b-13c20a089eca
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-06-12T10:47:40Z"
    creationTimestamp: "2026-06-12T10:42:37Z"
    generateName: longhorn-admission-webhook-
    generation: 6
    labels:
      app: longhorn-admission-webhook
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.11.2
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: longhorn-1.11.2
      kubernetes.io/service-name: longhorn-admission-webhook
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:helm.sh/chart: {}
            f:kubernetes.io/service-name: {}
            f:objectset.rio.cattle.io/hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"96be54fd-598b-43a9-88cb-fbc5f6346614"}: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-06-12T10:47:40Z"
    name: longhorn-admission-webhook-4q565
    namespace: longhorn-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: longhorn-admission-webhook
      uid: 96be54fd-598b-43a9-88cb-fbc5f6346614
    resourceVersion: "12066"
    uid: 9ccf4ebe-d732-489b-bb69-bbbd4ae6eb49
  ports:
  - name: admission-webhook
    port: 9502
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.42
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: hp-117-tink-system
    targetRef:
      kind: Pod
      name: longhorn-manager-bvg2r
      namespace: longhorn-system
      uid: f69f3692-00cb-4087-b546-1f5985ef9619
  - addresses:
    - 10.52.1.5
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: hp-150-tink-system
    targetRef:
      kind: Pod
      name: longhorn-manager-l4qr4
      namespace: longhorn-system
      uid: 777ca1c3-22e8-4721-b43d-188ab4933a86
  - addresses:
    - 10.52.2.8
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: hp-69-tink-system
    targetRef:
      kind: Pod
      name: longhorn-manager-prlhd
      namespace: longhorn-system
      uid: b85fcfb0-d2a1-4ac3-b81b-13c20a089eca
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-06-12T10:47:40Z"
    creationTimestamp: "2026-06-12T10:42:37Z"
    generateName: longhorn-backend-
    generation: 6
    labels:
      app: longhorn-manager
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.11.2
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: longhorn-1.11.2
      kubernetes.io/service-name: longhorn-backend
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:helm.sh/chart: {}
            f:kubernetes.io/service-name: {}
            f:objectset.rio.cattle.io/hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"0553a576-225b-449b-8707-c489d6584746"}: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-06-12T10:47:40Z"
    name: longhorn-backend-lv8kj
    namespace: longhorn-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: longhorn-backend
      uid: 0553a576-225b-449b-8707-c489d6584746
    resourceVersion: "12067"
    uid: 7e8986d3-1e33-49c3-9d45-38228fc27cf5
  ports:
  - name: manager
    port: 9500
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.43
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: hp-117-tink-system
    targetRef:
      kind: Pod
      name: longhorn-ui-74c6fbbdb4-84ldd
      namespace: longhorn-system
      uid: 49b7b7a2-c9a5-4d3d-9c92-b9581f2fe458
  - addresses:
    - 10.52.0.45
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: hp-117-tink-system
    targetRef:
      kind: Pod
      name: longhorn-ui-74c6fbbdb4-q4c6l
      namespace: longhorn-system
      uid: 8cd15c4d-f923-4f71-aea7-5d522b25e0d2
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-06-12T10:42:47Z"
    creationTimestamp: "2026-06-12T10:42:37Z"
    generateName: longhorn-frontend-
    generation: 3
    labels:
      app: longhorn-ui
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.11.2
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: longhorn-1.11.2
      kubernetes.io/service-name: longhorn-frontend
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:helm.sh/chart: {}
            f:kubernetes.io/service-name: {}
            f:objectset.rio.cattle.io/hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"3b7071c2-f68b-4110-b48b-24a483401f72"}: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-06-12T10:42:47Z"
    name: longhorn-frontend-b55dh
    namespace: longhorn-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: longhorn-frontend
      uid: 3b7071c2-f68b-4110-b48b-24a483401f72
    resourceVersion: "5107"
    uid: 8a92987a-e86a-4576-87a0-ffe11d85aeda
  ports:
  - name: http
    port: 8000
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.52.0.42
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: hp-117-tink-system
    targetRef:
      kind: Pod
      name: longhorn-manager-bvg2r
      namespace: longhorn-system
      uid: f69f3692-00cb-4087-b546-1f5985ef9619
  - addresses:
    - 10.52.1.5
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: hp-150-tink-system
    targetRef:
      kind: Pod
      name: longhorn-manager-l4qr4
      namespace: longhorn-system
      uid: 777ca1c3-22e8-4721-b43d-188ab4933a86
  - addresses:
    - 10.52.2.8
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: hp-69-tink-system
    targetRef:
      kind: Pod
      name: longhorn-manager-prlhd
      namespace: longhorn-system
      uid: b85fcfb0-d2a1-4ac3-b81b-13c20a089eca
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2026-06-12T10:47:40Z"
    creationTimestamp: "2026-06-12T10:42:37Z"
    generateName: longhorn-recovery-backend-
    generation: 5
    labels:
      app: longhorn-recovery-backend
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.11.2
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      helm.sh/chart: longhorn-1.11.2
      kubernetes.io/service-name: longhorn-recovery-backend
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: discovery.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:addressType: {}
        f:endpoints: {}
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:endpointslice.kubernetes.io/managed-by: {}
            f:helm.sh/chart: {}
            f:kubernetes.io/service-name: {}
            f:objectset.rio.cattle.io/hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"22478905-0f13-4597-b408-461631c288dc"}: {}
        f:ports: {}
      manager: kube-controller-manager
      operation: Update
      time: "2026-06-12T10:47:40Z"
    name: longhorn-recovery-backend-vl6z8
    namespace: longhorn-system
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: longhorn-recovery-backend
      uid: 22478905-0f13-4597-b408-461631c288dc
    resourceVersion: "12071"
    uid: cab7c131-cf1b-4d9a-9564-780a14742a4b
  ports:
  - name: recovery-backend
    port: 9503
    protocol: TCP
kind: List
metadata:
  resourceVersion: "676475"
