apiVersion: v1
items:
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: backing-image-manager
    usage:
      cpu: 1514432n
      memory: 1326844Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      longhorn.io/component: backing-image-manager
      longhorn.io/disk-uuid: 4b5b9744-0b68-484b-9ec5-ec53982866a5
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: hp-117-tink-system
    name: bim-45022d9e83691d1125dccbd75b33d9cd1a585fd75ddcc59955d72280
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:30Z"
  window: 27.16s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: backing-image-manager
    usage:
      cpu: 1282744n
      memory: 1807760Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      longhorn.io/component: backing-image-manager
      longhorn.io/disk-uuid: 0d4ca67b-82b6-4b31-adac-1839e717453c
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: hp-150-tink-system
    name: bim-4dfba11530c5606d4b02ee7f6deece071a37e52b3d8e29fa18e09e0c
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:18Z"
  window: 11.208s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: backing-image-manager
    usage:
      cpu: 2781262n
      memory: 957328Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      longhorn.io/component: backing-image-manager
      longhorn.io/disk-uuid: 7d03df10-4376-40d4-bfea-a386ee4aeb1a
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: hp-69-tink-system
    name: bim-5ffc3fbebb12f12c37d2c9ab4bd0b9c56eb34b91572c16e842919ed1
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:26Z"
  window: 12.339s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-attacher
    usage:
      cpu: 555028n
      memory: 16580Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: csi-attacher
      pod-template-hash: 789565cff6
    name: csi-attacher-789565cff6-46ghm
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:29Z"
  window: 19.808s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-attacher
    usage:
      cpu: 427401n
      memory: 15112Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: csi-attacher
      pod-template-hash: 789565cff6
    name: csi-attacher-789565cff6-jt6lq
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:25Z"
  window: 12.459s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-attacher
    usage:
      cpu: 686154n
      memory: 20068Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: csi-attacher
      pod-template-hash: 789565cff6
    name: csi-attacher-789565cff6-wxzxs
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:26Z"
  window: 11.751s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-provisioner
    usage:
      cpu: 2267175n
      memory: 31540Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: csi-provisioner
      pod-template-hash: 9bf959487
    name: csi-provisioner-9bf959487-4vkc2
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:19Z"
  window: 14.556s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-provisioner
    usage:
      cpu: 860542n
      memory: 18588Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: csi-provisioner
      pod-template-hash: 9bf959487
    name: csi-provisioner-9bf959487-kkzt8
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:32Z"
  window: 17.439s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-provisioner
    usage:
      cpu: 961920n
      memory: 18464Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: csi-provisioner
      pod-template-hash: 9bf959487
    name: csi-provisioner-9bf959487-zqqjv
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:31Z"
  window: 25.604s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-resizer
    usage:
      cpu: 407606n
      memory: 17364Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: csi-resizer
      pod-template-hash: 5d694ff569
    name: csi-resizer-5d694ff569-2fzck
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:22Z"
  window: 13.41s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-resizer
    usage:
      cpu: 739187n
      memory: 17504Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: csi-resizer
      pod-template-hash: 5d694ff569
    name: csi-resizer-5d694ff569-fsg94
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:16Z"
  window: 25.087s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-resizer
    usage:
      cpu: 547229n
      memory: 17576Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: csi-resizer
      pod-template-hash: 5d694ff569
    name: csi-resizer-5d694ff569-j74gj
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:15Z"
  window: 14.853s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-snapshotter
    usage:
      cpu: 919243n
      memory: 14552Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: csi-snapshotter
      pod-template-hash: 678c9588c4
    name: csi-snapshotter-678c9588c4-2t2gw
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:28Z"
  window: 17.175s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-snapshotter
    usage:
      cpu: 402540n
      memory: 18104Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: csi-snapshotter
      pod-template-hash: 678c9588c4
    name: csi-snapshotter-678c9588c4-jt7tf
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:27Z"
  window: 12.046s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: csi-snapshotter
    usage:
      cpu: 471597n
      memory: 20508Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: csi-snapshotter
      pod-template-hash: 678c9588c4
    name: csi-snapshotter-678c9588c4-mt4mp
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:30Z"
  window: 16.196s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: engine-image-ei-c9fa6d45
    usage:
      cpu: 23982346n
      memory: 2072Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      controller-revision-hash: 577649bb5c
      longhorn.io/component: engine-image
      longhorn.io/engine-image: ei-c9fa6d45
      pod-template-generation: "1"
    name: engine-image-ei-c9fa6d45-d5b7t
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:31Z"
  window: 19.769s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: engine-image-ei-c9fa6d45
    usage:
      cpu: 13365379n
      memory: 2116Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      controller-revision-hash: 577649bb5c
      longhorn.io/component: engine-image
      longhorn.io/engine-image: ei-c9fa6d45
      pod-template-generation: "1"
    name: engine-image-ei-c9fa6d45-vj88m
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:22Z"
  window: 10.693s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: engine-image-ei-c9fa6d45
    usage:
      cpu: 16604933n
      memory: 2180Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      controller-revision-hash: 577649bb5c
      longhorn.io/component: engine-image
      longhorn.io/engine-image: ei-c9fa6d45
      pod-template-generation: "1"
    name: engine-image-ei-c9fa6d45-zjtt7
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:23Z"
  window: 17.392s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: instance-manager
    usage:
      cpu: 12023403n
      memory: 167536Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      longhorn.io/component: instance-manager
      longhorn.io/data-engine: v1
      longhorn.io/instance-manager-image: imi-0f0c2602
      longhorn.io/instance-manager-type: aio
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: hp-117-tink-system
    name: instance-manager-7742e04beb074c12e693076a0d1c6595
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:29Z"
  window: 17.647s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: instance-manager
    usage:
      cpu: 7395628n
      memory: 161168Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      longhorn.io/component: instance-manager
      longhorn.io/data-engine: v1
      longhorn.io/instance-manager-image: imi-0f0c2602
      longhorn.io/instance-manager-type: aio
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: hp-150-tink-system
    name: instance-manager-c5b8e6cd15853ab91e2d95ce832eb8b5
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:32Z"
  window: 21.505s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: instance-manager
    usage:
      cpu: 31099540n
      memory: 194660Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      longhorn.io/component: instance-manager
      longhorn.io/data-engine: v1
      longhorn.io/instance-manager-image: imi-0f0c2602
      longhorn.io/instance-manager-type: aio
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: hp-69-tink-system
    name: instance-manager-f7924585cf5aadacce1b397379d2df82
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:23Z"
  window: 19.158s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-csi-plugin
    usage:
      cpu: 660253n
      memory: 22552Ki
  - name: longhorn-liveness-probe
    usage:
      cpu: 1148404n
      memory: 19256Ki
  - name: node-driver-registrar
    usage:
      cpu: 290753n
      memory: 11196Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: longhorn-csi-plugin
      controller-revision-hash: 685686b46c
      pod-template-generation: "1"
    name: longhorn-csi-plugin-ctt87
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:22Z"
  window: 15.451s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-csi-plugin
    usage:
      cpu: 729744n
      memory: 31260Ki
  - name: longhorn-liveness-probe
    usage:
      cpu: 740546n
      memory: 21840Ki
  - name: node-driver-registrar
    usage:
      cpu: 43885n
      memory: 12476Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: longhorn-csi-plugin
      controller-revision-hash: 685686b46c
      pod-template-generation: "1"
    name: longhorn-csi-plugin-fvzv6
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:21Z"
  window: 17.772s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: node-driver-registrar
    usage:
      cpu: 34461n
      memory: 11208Ki
  - name: longhorn-csi-plugin
    usage:
      cpu: 244217n
      memory: 32868Ki
  - name: longhorn-liveness-probe
    usage:
      cpu: 446100n
      memory: 17404Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: longhorn-csi-plugin
      controller-revision-hash: 685686b46c
      pod-template-generation: "1"
    name: longhorn-csi-plugin-rvc6j
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:15Z"
  window: 17.509s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-driver-deployer
    usage:
      cpu: "0"
      memory: 16788Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: longhorn-driver-deployer
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.11.2
      helm.sh/chart: longhorn-1.11.2
      pod-template-hash: 776db5d949
    name: longhorn-driver-deployer-776db5d949-22bp4
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:29Z"
  window: 15.975s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-manager
    usage:
      cpu: 7793255n
      memory: 241104Ki
  - name: pre-pull-share-manager-image
    usage:
      cpu: "0"
      memory: 440Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: longhorn-manager
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.11.2
      controller-revision-hash: 64c59999ff
      helm.sh/chart: longhorn-1.11.2
      longhorn.io/admission-webhook: longhorn-admission-webhook
      longhorn.io/recovery-backend: longhorn-recovery-backend
      pod-template-generation: "1"
    name: longhorn-manager-bvg2r
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:20Z"
  window: 16.992s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-manager
    usage:
      cpu: 8194528n
      memory: 242096Ki
  - name: pre-pull-share-manager-image
    usage:
      cpu: "0"
      memory: 448Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: longhorn-manager
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.11.2
      controller-revision-hash: 64c59999ff
      helm.sh/chart: longhorn-1.11.2
      longhorn.io/admission-webhook: longhorn-admission-webhook
      longhorn.io/recovery-backend: longhorn-recovery-backend
      pod-template-generation: "1"
    name: longhorn-manager-l4qr4
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:21Z"
  window: 21.818s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-manager
    usage:
      cpu: 21752829n
      memory: 258288Ki
  - name: pre-pull-share-manager-image
    usage:
      cpu: "0"
      memory: 512Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: longhorn-manager
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.11.2
      controller-revision-hash: 64c59999ff
      helm.sh/chart: longhorn-1.11.2
      longhorn.io/admission-webhook: longhorn-admission-webhook
      longhorn.io/recovery-backend: longhorn-recovery-backend
      pod-template-generation: "1"
    name: longhorn-manager-prlhd
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:23Z"
  window: 16.612s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-ui
    usage:
      cpu: "0"
      memory: 2788Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: longhorn-ui
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.11.2
      helm.sh/chart: longhorn-1.11.2
      pod-template-hash: 74c6fbbdb4
    name: longhorn-ui-74c6fbbdb4-84ldd
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:18Z"
  window: 15.198s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: longhorn-ui
    usage:
      cpu: "0"
      memory: 2784Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2026-06-12T23:12:38Z"
    labels:
      app: longhorn-ui
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.11.2
      helm.sh/chart: longhorn-1.11.2
      pod-template-hash: 74c6fbbdb4
    name: longhorn-ui-74c6fbbdb4-q4c6l
    namespace: longhorn-system
  timestamp: "2026-06-12T23:12:31Z"
  window: 26.718s
kind: List
metadata: {}
