apiVersion: v1
items:
- apiVersion: v1
  data:
    applied-checksum: OTQ0Nzc1NmQxNjc2YWJmNDdhMDMyNjA2YTc2YmI4OWFkMzVlZmQ2NDAxODc1NDU0M2QzOWMwNmMwZmIzMjdjZA==
    applied-output: H4sIAAAAAAAA/6quBQQAAP//Q7+mowIAAAA=
    applied-periodic-output: H4sIAAAAAAAA/6quBQQAAP//Q7+mowIAAAA=
    failed-checksum: "null"
    failed-output: "null"
    failure-count: MA==
    failure-threshold: MQ==
    last-apply-time: RnJpIEp1biAxMiAxMDo0ODo1NCBVVEMgMjAyNg==
    max-failures: LTE=
    probe-statuses: eyJjYWxpY28iOnsiaGVhbHRoeSI6dHJ1ZSwic3VjY2Vzc0NvdW50IjoxfSwiZXRjZCI6eyJoZWFsdGh5Ijp0cnVlLCJzdWNjZXNzQ291bnQiOjF9LCJrdWJlLWFwaXNlcnZlciI6eyJoZWFsdGh5Ijp0cnVlLCJzdWNjZXNzQ291bnQiOjF9LCJrdWJlLWNvbnRyb2xsZXItbWFuYWdlciI6eyJoZWFsdGh5Ijp0cnVlLCJzdWNjZXNzQ291bnQiOjF9LCJrdWJlLXNjaGVkdWxlciI6eyJoZWFsdGh5Ijp0cnVlLCJzdWNjZXNzQ291bnQiOjF9LCJrdWJlbGV0Ijp7ImhlYWx0aHkiOnRydWUsInN1Y2Nlc3NDb3VudCI6MX19
    success-count: Mw==
  kind: Secret
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4xTwW7bOhD8lYc9i36SItGSgF6K9pRDgRx6qXtYrpaxKooUSCppYOjfCzlxGzuRkSPJmdnZ4e4BBo7YYkRoDoDWuoixczYsR6d+McXAceM7tyGM0fCmc/93LTTgexbKuRiixxGSVbB7tOzF/UP/zHn18pAl/912tv10d/v184eVLA4MDdAUohvEjUTKUOeU6uJD1DAiLXxtmKMwjtBAcmHMoGIToIHDDvboHzhE9nvqlrcBLd5zu4NmB9FPvIMZ5gROlAOQmRb45rfoq7AwXi5Oxk8lV4ShOcpe6WWPYQ8NyCJt03ZbVFmZYUU5EWm9laQq3nKRKizzTFVULt1xcJMnDq9UFFI/jf+qnSew4vkC5Gz0zojRoGXhneE1OY7UXgUMSPvOsjhOVqVK3bLmPM+1KnJN2/qG6haLSkqmmlBilZd1ptqyJEmFZiVTTlWRZWWt18WvTs45xbr2L34/ClmL2NlehKcQeXiDfnS+Z3/W4JzAejlxcrQkB8/I9+fyOLd3rNmzJQ7Q/DgAjt139qFz9p2NggSUcdR/W4hf2HA84hZPCbx8mGF/uuk7uyR+sYBXg5qOf1RwWW4ZU5HKOhcFsxS12qIgmRaYViUx3cD8c04gPo38xuhZAPOfAAAA////aXlDhQQAAA
      objectset.rio.cattle.io/id: rke-bootstrap
      objectset.rio.cattle.io/owner-gvk: rke.cattle.io/v1, Kind=RKEBootstrap
      objectset.rio.cattle.io/owner-name: custom-36ac1af2c0f4
      objectset.rio.cattle.io/owner-namespace: fleet-local
      rke.cattle.io/join-url: https://10.115.252.96:9345
      rke.cattle.io/joined-to: https://10.115.252.86:9345
      rke.cattle.io/labels: '{"harvesterhci.io/managed":"true"}'
      rke.cattle.io/plan-last-updated: "2026-06-12T10:48:54Z"
      rke.cattle.io/plan-probes-passed: "2026-06-12T10:49:37Z"
    creationTimestamp: "2026-06-12T10:45:19Z"
    labels:
      cluster.x-k8s.io/cluster-name: local
      harvesterhci.io/managed: "true"
      objectset.rio.cattle.io/hash: 640d0d748151a8c2cccff76cb8e7e40ba521b8c5
      resources.cattle.io/backup: "true"
      rke.cattle.io/cluster-name: local
      rke.cattle.io/control-plane-role: "true"
      rke.cattle.io/etcd-role: "true"
      rke.cattle.io/machine-id: 8b5fdefe222fb42fc793c9da4866ec9ca6a82591bd55c6c4feb60e0b41159fe
      rke.cattle.io/machine-name: custom-36ac1af2c0f4
      rke.cattle.io/node-name: hp-69-tink-system
      rke.cattle.io/worker-role: "true"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:rke.cattle.io/control-plane-role: {}
            f:rke.cattle.io/etcd-role: {}
      manager: kubectl-label
      operation: Update
      time: "2026-06-12T10:48:54Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:appliedPlan: {}
          f:failure-threshold: {}
          f:max-failures: {}
          f:plan: {}
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
            f:rke.cattle.io/join-url: {}
            f:rke.cattle.io/joined-to: {}
            f:rke.cattle.io/labels: {}
            f:rke.cattle.io/plan-last-updated: {}
            f:rke.cattle.io/plan-probes-passed: {}
          f:labels:
            .: {}
            f:cluster.x-k8s.io/cluster-name: {}
            f:harvesterhci.io/managed: {}
            f:objectset.rio.cattle.io/hash: {}
            f:resources.cattle.io/backup: {}
            f:rke.cattle.io/cluster-name: {}
            f:rke.cattle.io/machine-id: {}
            f:rke.cattle.io/machine-name: {}
            f:rke.cattle.io/node-name: {}
            f:rke.cattle.io/worker-role: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4e557ea0-0692-4ee6-9b7a-c604a085cec3"}: {}
        f:type: {}
      manager: rancher
      operation: Update
      time: "2026-06-12T10:49:37Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:applied-checksum: {}
          f:applied-output: {}
          f:applied-periodic-output: {}
          f:failed-checksum: {}
          f:failed-output: {}
          f:failure-count: {}
          f:last-apply-time: {}
          f:probe-statuses: {}
          f:success-count: {}
      manager: rancher-system-agent
      operation: Update
      time: "2026-06-12T14:38:02Z"
    name: custom-36ac1af2c0f4-machine-plan
    namespace: fleet-local
    ownerReferences:
    - apiVersion: rke.cattle.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: RKEBootstrap
      name: custom-36ac1af2c0f4
      uid: 4e557ea0-0692-4ee6-9b7a-c604a085cec3
    resourceVersion: "261222"
    uid: c4e2cb12-7245-4349-aa46-88b4b65a06e7
  type: rke.cattle.io/machine-plan
- apiVersion: v1
  data:
    applied-checksum: MzY5NGE5NmU2ZWQ1NGExNGNkYjk2M2Q2ZTk1OWQzMzRlYWExZmQyNWY1YzJlZjI2MzBlYThjMmM0OGJkZTIwZA==
    applied-output: H4sIAAAAAAAA/6quBQQAAP//Q7+mowIAAAA=
    applied-periodic-output: H4sIAAAAAAAA/6quBQQAAP//Q7+mowIAAAA=
    failed-checksum: "null"
    failed-output: "null"
    failure-count: MA==
    failure-threshold: MQ==
    last-apply-time: RnJpIEp1biAxMiAxMDo0NToyNyBVVEMgMjAyNg==
    max-failures: LTE=
    probe-statuses: eyJjYWxpY28iOnsiaGVhbHRoeSI6dHJ1ZSwic3VjY2Vzc0NvdW50IjoxfSwiZXRjZCI6eyJoZWFsdGh5Ijp0cnVlLCJzdWNjZXNzQ291bnQiOjF9LCJrdWJlLWFwaXNlcnZlciI6eyJoZWFsdGh5Ijp0cnVlLCJzdWNjZXNzQ291bnQiOjF9LCJrdWJlLWNvbnRyb2xsZXItbWFuYWdlciI6eyJoZWFsdGh5Ijp0cnVlLCJzdWNjZXNzQ291bnQiOjF9LCJrdWJlLXNjaGVkdWxlciI6eyJoZWFsdGh5Ijp0cnVlLCJzdWNjZXNzQ291bnQiOjF9LCJrdWJlbGV0Ijp7ImhlYWx0aHkiOnRydWUsInN1Y2Nlc3NDb3VudCI6MX19
    success-count: MQ==
  kind: Secret
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yTMW/bMBCF/0pxs+jSkkhKBroU7ZShQIYuRYcjeaxV0aRAUkmDwP+9kJO0dmIbGUV97+7x8e4RdlTQYkHYPAKGEAuWIYa8fEb9m0zJVFZpiCuDpXhaDfHjYGEDaSSmYyy5JJygugjH+0CJ/bobnzRHf+7W1YebIdhPtzdfP7+7UsAdwQbMnEvcMeV402muHe/4u6R5QrPonScqzEeDHvYVeNTkD5c2fs6F0uoPG7u8aJ8PXho/SaozXAwlRc8mj2EBS5rpiqUt5i1sQOi1QEnctY2SvWrbXlpTC26pbvqubRV23DnZQQWJcpyToXxURaMZ5+l/t9OEL1h/BR37Zil6ulSOirFXgR2a7RCIHQYEnakt1qrWTkhnGnINWbJG91bWLfI1b62rJa+567peCUStJTdWNk1tbHOx+NUBOJWEaP/x24mt14qVIYwsP+RCuzf4fUwjpZMb7iu43I+9WFqigyfy3HxVcJi/W3KUKBjKsPnxCDgN3ynlIYYzmwEVaB/N+G0RfiFP5cAtnip4fjFP6eVkHMIS+atFuprUfHgky4WQjRPMOCVY29SKoZCCqVppdH1vWtHC/ue+gvIw0RujJwHs/wYAAP//6P4PPk0EAAA
      objectset.rio.cattle.io/id: rke-bootstrap
      objectset.rio.cattle.io/owner-gvk: rke.cattle.io/v1, Kind=RKEBootstrap
      objectset.rio.cattle.io/owner-name: custom-7f038b0bf080
      objectset.rio.cattle.io/owner-namespace: fleet-local
      rke.cattle.io/join-url: https://10.115.252.86:9345
      rke.cattle.io/joined-to: "null"
      rke.cattle.io/plan-last-updated: "2026-06-12T10:45:24Z"
      rke.cattle.io/plan-probes-passed: "2026-06-12T10:45:40Z"
    creationTimestamp: "2026-06-12T10:45:24Z"
    labels:
      cluster.x-k8s.io/cluster-name: local
      cluster.x-k8s.io/control-plane: "true"
      objectset.rio.cattle.io/hash: 5b15a6e0f4376974496dc250de2398447a80ff68
      resources.cattle.io/backup: "true"
      rke.cattle.io/cluster-name: local
      rke.cattle.io/control-plane-role: "true"
      rke.cattle.io/etcd-role: "true"
      rke.cattle.io/init-node: "true"
      rke.cattle.io/machine-id: afc2da272bf56fc3ef3ededcb9d624a0104df26020f88975aabb60cd6332cd3
      rke.cattle.io/machine-name: custom-7f038b0bf080
      rke.cattle.io/node-name: hp-117-tink-system
      rke.cattle.io/worker-role: "true"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:applied-checksum: {}
          f:applied-output: {}
          f:applied-periodic-output: {}
          f:failed-checksum: {}
          f:failed-output: {}
          f:failure-count: {}
          f:last-apply-time: {}
          f:probe-statuses: {}
          f:success-count: {}
      manager: rancher-system-agent
      operation: Update
      time: "2026-06-12T10:46:15Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:appliedPlan: {}
          f:failure-threshold: {}
          f:max-failures: {}
          f:plan: {}
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
            f:rke.cattle.io/join-url: {}
            f:rke.cattle.io/joined-to: {}
            f:rke.cattle.io/plan-last-updated: {}
            f:rke.cattle.io/plan-probes-passed: {}
          f:labels:
            .: {}
            f:cluster.x-k8s.io/cluster-name: {}
            f:cluster.x-k8s.io/control-plane: {}
            f:objectset.rio.cattle.io/hash: {}
            f:resources.cattle.io/backup: {}
            f:rke.cattle.io/cluster-name: {}
            f:rke.cattle.io/control-plane-role: {}
            f:rke.cattle.io/etcd-role: {}
            f:rke.cattle.io/init-node: {}
            f:rke.cattle.io/machine-id: {}
            f:rke.cattle.io/machine-name: {}
            f:rke.cattle.io/node-name: {}
            f:rke.cattle.io/worker-role: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"d05563f5-cf75-4327-a565-727baf99c454"}: {}
        f:type: {}
      manager: rancher
      operation: Update
      time: "2026-06-12T10:47:03Z"
    name: custom-7f038b0bf080-machine-plan
    namespace: fleet-local
    ownerReferences:
    - apiVersion: rke.cattle.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: RKEBootstrap
      name: custom-7f038b0bf080
      uid: d05563f5-cf75-4327-a565-727baf99c454
    resourceVersion: "10460"
    uid: 06a4bf87-fecd-4915-8ef2-44223b3129e1
  type: rke.cattle.io/machine-plan
- apiVersion: v1
  data:
    applied-checksum: ZjY1OTk3OGRmZmIxOTNhZjlhMjcwNGMzMzVmMDc4ZGI1YWYyMGU5MGYwOWE3ZTFmZThlYmUyNjU1OTI5MWUxNw==
    applied-output: H4sIAAAAAAAA/6quBQQAAP//Q7+mowIAAAA=
    applied-periodic-output: H4sIAAAAAAAA/6quBQQAAP//Q7+mowIAAAA=
    failed-checksum: "null"
    failed-output: "null"
    failure-count: MA==
    failure-threshold: MQ==
    last-apply-time: RnJpIEp1biAxMiAxMDo0Nzo0MyBVVEMgMjAyNg==
    max-failures: LTE=
    probe-statuses: eyJjYWxpY28iOnsiaGVhbHRoeSI6dHJ1ZSwic3VjY2Vzc0NvdW50IjoxfSwiZXRjZCI6eyJoZWFsdGh5Ijp0cnVlLCJzdWNjZXNzQ291bnQiOjF9LCJrdWJlLWFwaXNlcnZlciI6eyJoZWFsdGh5Ijp0cnVlLCJzdWNjZXNzQ291bnQiOjF9LCJrdWJlLWNvbnRyb2xsZXItbWFuYWdlciI6eyJoZWFsdGh5Ijp0cnVlLCJzdWNjZXNzQ291bnQiOjF9LCJrdWJlLXNjaGVkdWxlciI6eyJoZWFsdGh5Ijp0cnVlLCJzdWNjZXNzQ291bnQiOjF9LCJrdWJlbGV0Ijp7ImhlYWx0aHkiOnRydWUsInN1Y2Nlc3NDb3VudCI6MX19
    success-count: Mw==
  kind: Secret
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4xTwW7bOhD8lYc9i34UJYuSgF6K9pRDgRx6qXtYUstYFU0KJJU0MPTvhZy4jZPIyJHLmdnhcPcIB0rYYUJoj4DO+YSp9y4uR69+kU6R0ib0fqMxJUub3v/fd9BCGIgp71NMAUfIVsH+wVFgd/fDE+fFzX2e/XfTu+7T7c3Xzx9WcnggaEFPMfkDq6tGcKVImir/EDWOqBe+sUSJWa/RQvbKmEVFNkILxx3sMdxTTBT2ul/uDujwjrodtDtIYaIdzDBncKYcQdtpgW9+s6GOC+O5cDZ+brkiDO1J9spb9hj30EJTSYFbTrzIsVFV05EWheRCGCorUcuO19jw7ZJKoOinoCm+UFGoh2n81+0ygRXPr0DepeAtGy06YsFbWpOjpLurgAPqfe+InSarKExV6Yors0WJQoq6KZU2olsKVHFjBC9rmUu51VxQJU1Z5aVQqGRhaLsqfnVyLinOd3/x+5HlW85S7wYWH2Oiwxv4gw8DhYsXzhms92NnS0t08IR8fzBPg3tLhgI5TRHaH0fAsf9OIfbevbNSkIGyXg/fFuIXspROuMVTBs8/ZimcK0PvlshfbeDVpKbTJ5UdV4VqctZxiawUWjMs8pwZUxvipdZacZh/zhmkx5HeGL0IYP4TAAD//9icrSCGBAAA
      objectset.rio.cattle.io/id: rke-bootstrap
      objectset.rio.cattle.io/owner-gvk: rke.cattle.io/v1, Kind=RKEBootstrap
      objectset.rio.cattle.io/owner-name: custom-86920bbe7f61
      objectset.rio.cattle.io/owner-namespace: fleet-local
      rke.cattle.io/join-url: https://10.115.252.95:9345
      rke.cattle.io/joined-to: https://10.115.252.86:9345
      rke.cattle.io/labels: '{"harvesterhci.io/managed":"true"}'
      rke.cattle.io/plan-last-updated: "2026-06-12T10:47:43Z"
      rke.cattle.io/plan-probes-passed: "2026-06-12T10:48:23Z"
    creationTimestamp: "2026-06-12T10:45:19Z"
    labels:
      cluster.x-k8s.io/cluster-name: local
      harvesterhci.io/managed: "true"
      objectset.rio.cattle.io/hash: 9672a50e031a9b69dec237022fe46287d08a9051
      resources.cattle.io/backup: "true"
      rke.cattle.io/cluster-name: local
      rke.cattle.io/control-plane-role: "true"
      rke.cattle.io/etcd-role: "true"
      rke.cattle.io/machine-id: 33f66c60bf5a7a272894bcf2dbf5ae60ff204871775c02e67f46142bab73fe5
      rke.cattle.io/machine-name: custom-86920bbe7f61
      rke.cattle.io/node-name: hp-150-tink-system
      rke.cattle.io/worker-role: "true"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:rke.cattle.io/control-plane-role: {}
            f:rke.cattle.io/etcd-role: {}
      manager: kubectl-label
      operation: Update
      time: "2026-06-12T10:47:43Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:appliedPlan: {}
          f:failure-threshold: {}
          f:max-failures: {}
          f:plan: {}
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
            f:rke.cattle.io/join-url: {}
            f:rke.cattle.io/joined-to: {}
            f:rke.cattle.io/labels: {}
            f:rke.cattle.io/plan-last-updated: {}
            f:rke.cattle.io/plan-probes-passed: {}
          f:labels:
            .: {}
            f:cluster.x-k8s.io/cluster-name: {}
            f:harvesterhci.io/managed: {}
            f:objectset.rio.cattle.io/hash: {}
            f:resources.cattle.io/backup: {}
            f:rke.cattle.io/cluster-name: {}
            f:rke.cattle.io/machine-id: {}
            f:rke.cattle.io/machine-name: {}
            f:rke.cattle.io/node-name: {}
            f:rke.cattle.io/worker-role: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4d0b3b91-d07a-42cc-a311-ff8fe04cccb0"}: {}
        f:type: {}
      manager: rancher
      operation: Update
      time: "2026-06-12T10:48:23Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:applied-checksum: {}
          f:applied-output: {}
          f:applied-periodic-output: {}
          f:failed-checksum: {}
          f:failed-output: {}
          f:failure-count: {}
          f:last-apply-time: {}
          f:probe-statuses: {}
          f:success-count: {}
      manager: rancher-system-agent
      operation: Update
      time: "2026-06-12T14:31:38Z"
    name: custom-86920bbe7f61-machine-plan
    namespace: fleet-local
    ownerReferences:
    - apiVersion: rke.cattle.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: RKEBootstrap
      name: custom-86920bbe7f61
      uid: 4d0b3b91-d07a-42cc-a311-ff8fe04cccb0
    resourceVersion: "255087"
    uid: c54f765a-f921-4dff-ba4a-df9fc9ff8eb9
  type: rke.cattle.io/machine-plan
kind: List
metadata:
  resourceVersion: "676218"
