apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SST48TMQzFvwryOSmZ7vzbkbggOO0BaQ9cEAfH46Fh0rhK3HKo5rujKVpYVrRajon9s+z33hn2rDiiIgxnwJREUYOksj7Ff2fSwrrJQTaEqpE3Qd6GEQbIM1svokUzHsBcbZYfibP9dpp/Mc8qp8q8eQhpfPf48PH9qycl3DMMQMeisrd3LVKF05bcVL8KLQeklZ8is9oohBEWAxE9x5tH77DsYIC2dqMbu7qvmgp72hLRNHUt+Z47rp3HZlv5nhowL67dI+1C4tv7/43kmX8r/D9c4XwKxBaJ5JjUZokr+setxcD1cfZp0+fuXpPOwEXaR544cyIuMHw5Ax7CZ84lSPqH6WDAR6H50wp+4Mh66dN8ZAMkSbPEyPnpZw5pjduLjNxU43gJaM1N0zE669r7ra2ZW3vvO7TUuhpd3xDTHSxfl+VnAAAA///qU3XhBAMAAA
      objectset.rio.cattle.io/id: rke-bootstrap
      objectset.rio.cattle.io/owner-gvk: rke.cattle.io/v1, Kind=RKEBootstrap
      objectset.rio.cattle.io/owner-name: custom-36ac1af2c0f4
      objectset.rio.cattle.io/owner-namespace: fleet-local
      rancher.io/service-account.secret-ref: fleet-local/custom-36ac1af2c0f4-machine-bootstrap-token-jpw9x
    creationTimestamp: "2026-06-12T10:45:19Z"
    labels:
      objectset.rio.cattle.io/hash: 640d0d748151a8c2cccff76cb8e7e40ba521b8c5
      rke.cattle.io/machine-name: custom-36ac1af2c0f4
      rke.cattle.io/rkebootstrap-name: custom-36ac1af2c0f4
      rke.cattle.io/service-account-role: bootstrap
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
            f:rancher.io/service-account.secret-ref: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
            f:rke.cattle.io/machine-name: {}
            f:rke.cattle.io/rkebootstrap-name: {}
            f:rke.cattle.io/service-account-role: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4e557ea0-0692-4ee6-9b7a-c604a085cec3"}: {}
      manager: rancher
      operation: Update
      time: "2026-06-12T10:45:19Z"
    name: custom-36ac1af2c0f4-machine-bootstrap
    namespace: fleet-local
    ownerReferences:
    - apiVersion: rke.cattle.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: RKEBootstrap
      name: custom-36ac1af2c0f4
      uid: 4e557ea0-0692-4ee6-9b7a-c604a085cec3
    resourceVersion: "8804"
    uid: 1804fdeb-dbcd-48ca-b234-ce0a96541830
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SSP4/TQBDFvwqa2hvsnP+dJRoE1RVIV9AgitnxM1m82Y12J6GI/N2Rgw7BwUW50t73e/PvnWkP5ZGVaTgThxCV1cWQ189ov0M0QzfJxY2wqsfGxbdupIHSDGNj1KyJD1S8KI4/ApL5dpp/MX+8nKrizYML47vHh4/vb3YKvAcNJMescW/uWpaKp62UU30Tmg8sKz95QI2Pwp6Wgjxb+KtD7zjvaKC2Lsdy7Oq+airuZSsi09S1Ynt0qEvLzbayvTRUPJt2z7JzAdf7/xs5eA4mQxL0CmaenFf5Px5pxu8rvaZ2Rjo5gWGReAxqUvQreqmxFHR7Oy8tvaDLUR4xISEIMg1fzsQH9xkpuxj+ExcqyPoo86cV/AAPveg0HVGQxKApeo/09Gd2YQ3qs3Rd3cHxEu0aTdOBS1O291tTA625tx0bacuay74RyB0tX5flZwAAAP//Aj1E0j4DAAA
      objectset.rio.cattle.io/id: rke-bootstrap
      objectset.rio.cattle.io/owner-gvk: rke.cattle.io/v1, Kind=RKEBootstrap
      objectset.rio.cattle.io/owner-name: custom-36ac1af2c0f4
      objectset.rio.cattle.io/owner-namespace: fleet-local
      rancher.io/service-account.secret-ref: fleet-local/custom-36ac1af2c0f4-machine-plan-token-nfvqh
    creationTimestamp: "2026-06-12T10:45:19Z"
    labels:
      objectset.rio.cattle.io/hash: 640d0d748151a8c2cccff76cb8e7e40ba521b8c5
      rke.cattle.io/machine-name: custom-36ac1af2c0f4
      rke.cattle.io/plan-secret-name: custom-36ac1af2c0f4-machine-plan
      rke.cattle.io/rkebootstrap-name: custom-36ac1af2c0f4
      rke.cattle.io/service-account-role: plan
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
            f:rancher.io/service-account.secret-ref: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
            f:rke.cattle.io/machine-name: {}
            f:rke.cattle.io/plan-secret-name: {}
            f:rke.cattle.io/rkebootstrap-name: {}
            f:rke.cattle.io/service-account-role: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4e557ea0-0692-4ee6-9b7a-c604a085cec3"}: {}
      manager: rancher
      operation: Update
      time: "2026-06-12T10:45:19Z"
    name: custom-36ac1af2c0f4-machine-plan
    namespace: fleet-local
    ownerReferences:
    - apiVersion: rke.cattle.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: RKEBootstrap
      name: custom-36ac1af2c0f4
      uid: 4e557ea0-0692-4ee6-9b7a-c604a085cec3
    resourceVersion: "8798"
    uid: f6338291-296c-4c63-accb-347e40c96e73
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SSQY/TMBCF/wqac1yyTRwnkbggOO0BaQ9cEIexM6Ymrqeyp+VQ5b+jFC0sK1qVoz3zjWbee2fYk+CEgjCeAVNiQQmcyvpk+52cFJJNDrxxKBJpE/htmGCEPJOyzFIk4wGqq838I1FW307zL+ZF5fRQvXkMaXr39Pjx/d2TEu4JRnDHIrxXxtdNb2vr676+Cy0HdCvvI5GoyA4jLBVEtBRvHr3DsoMRtH3Q2FHt28Z0g2nboZvcVtcTbZuhb1uDfe1910P16to9ul1IdHv/v5E802+F/4crlE/BkULn+JhEZY4r+setpYLr49Tzpi/dvSZdBRdpn8hTpuSowPjlDHgInymXwOkfpkMFNrKbP63gB4oklz7JR6rAcZLMMVJ+/plDWuP2KiM31TheAjrVWneN18p5o1XbbI1C3WlltsaiHwbX6haWr8vyMwAA//8ea2c8BAMAAA
      objectset.rio.cattle.io/id: rke-bootstrap
      objectset.rio.cattle.io/owner-gvk: rke.cattle.io/v1, Kind=RKEBootstrap
      objectset.rio.cattle.io/owner-name: custom-7f038b0bf080
      objectset.rio.cattle.io/owner-namespace: fleet-local
      rancher.io/service-account.secret-ref: fleet-local/custom-7f038b0bf080-machine-bootstrap-token-n8tvp
    creationTimestamp: "2026-06-12T10:45:24Z"
    labels:
      objectset.rio.cattle.io/hash: 5b15a6e0f4376974496dc250de2398447a80ff68
      rke.cattle.io/machine-name: custom-7f038b0bf080
      rke.cattle.io/rkebootstrap-name: custom-7f038b0bf080
      rke.cattle.io/service-account-role: bootstrap
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
            f:rancher.io/service-account.secret-ref: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
            f:rke.cattle.io/machine-name: {}
            f:rke.cattle.io/rkebootstrap-name: {}
            f:rke.cattle.io/service-account-role: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"d05563f5-cf75-4327-a565-727baf99c454"}: {}
      manager: rancher
      operation: Update
      time: "2026-06-12T10:45:24Z"
    name: custom-7f038b0bf080-machine-bootstrap
    namespace: fleet-local
    ownerReferences:
    - apiVersion: rke.cattle.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: RKEBootstrap
      name: custom-7f038b0bf080
      uid: d05563f5-cf75-4327-a565-727baf99c454
    resourceVersion: "9002"
    uid: 067ce524-03ad-4d08-814f-b15bc53db813
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SSP4/TQBDFvwqa2ht8sdf/JBoE1RVIV9AgivF4lize7ES7k1BE/u7IQYfgIFGutPf93vx7Z9iz4oSKMJwBYxRF9RLz+injdybNrJvkZUOoGnjj5a2fYIA0sxlFNGvCAxRXxfIjcjLfTvMv5o+X00Px5tHH6d3T48f3dztF3DMMQMessjetK6tuLEdXduVdaD4grbwLzGqCEAZYCgg4crg59A7zDgaw44PFhktXV23Tt3XdNxNtbTnxtuq7um6xK51rOiheTLtH2vnIt/v/GzkEjCYzJdYbmHl2XuX/eKSZf1/pNbUzp5MnNkgkx6gmSVjRS42lgPvbubb0Ai5HeWLHiSNxhuHLGfDgP3PKXuJ/4gIFjEFo/rSCHziwXnSajlwASdQkIXB6/jP7uAb1Rbpu7uB4ifZUWttUzhpyrTV1tW0N2saadtuO6PqealvD8nVZfgYAAP//IEdr3D4DAAA
      objectset.rio.cattle.io/id: rke-bootstrap
      objectset.rio.cattle.io/owner-gvk: rke.cattle.io/v1, Kind=RKEBootstrap
      objectset.rio.cattle.io/owner-name: custom-7f038b0bf080
      objectset.rio.cattle.io/owner-namespace: fleet-local
      rancher.io/service-account.secret-ref: fleet-local/custom-7f038b0bf080-machine-plan-token-hsvlj
    creationTimestamp: "2026-06-12T10:45:24Z"
    labels:
      objectset.rio.cattle.io/hash: 5b15a6e0f4376974496dc250de2398447a80ff68
      rke.cattle.io/machine-name: custom-7f038b0bf080
      rke.cattle.io/plan-secret-name: custom-7f038b0bf080-machine-plan
      rke.cattle.io/rkebootstrap-name: custom-7f038b0bf080
      rke.cattle.io/service-account-role: plan
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
            f:rancher.io/service-account.secret-ref: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
            f:rke.cattle.io/machine-name: {}
            f:rke.cattle.io/plan-secret-name: {}
            f:rke.cattle.io/rkebootstrap-name: {}
            f:rke.cattle.io/service-account-role: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"d05563f5-cf75-4327-a565-727baf99c454"}: {}
      manager: rancher
      operation: Update
      time: "2026-06-12T10:45:24Z"
    name: custom-7f038b0bf080-machine-plan
    namespace: fleet-local
    ownerReferences:
    - apiVersion: rke.cattle.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: RKEBootstrap
      name: custom-7f038b0bf080
      uid: d05563f5-cf75-4327-a565-727baf99c454
    resourceVersion: "8996"
    uid: 0ee93964-a60e-429e-be0c-18217acaf22e
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SSMY/TQBCF/wqa2hvWTs6OLdEgqK5AuoIGUcyOx2TxeifaHYci8n9HDjq4QyQKpb3zjd68984wsWKPitCdAWMURfUS8/op7juTZtZN8rIhVA288fLW99BBGtk4Ec2a8AjF1WH5ETmZb6fxF/Pi5VQWbx597N89PX58f/emiBNDBzRnlcns67ayznEz1OVdaD4irfwQmNUEIQywFBDQcbh59AHzATpo66bCB8t2W2Lr6rZnqraNraqBd3W1b3q7x9Y+rGJeXzshHXzk2/pfI2nk3w7/D5c5nTyxQSKZo5okYUX/pLUUcH2deVb6Mt1r1hVwsfaJB04ciTN0X86AR/+ZU/YS/xE6FOCC0PhpBT9wYL3MaZq5AJKoSULg9Pxn9HGt218duenGfCnorrdu69rS9LZBs6uIDG7L0gzDfmC7IyJnYfm6LD8DAAD//+5riLIEAwAA
      objectset.rio.cattle.io/id: rke-bootstrap
      objectset.rio.cattle.io/owner-gvk: rke.cattle.io/v1, Kind=RKEBootstrap
      objectset.rio.cattle.io/owner-name: custom-86920bbe7f61
      objectset.rio.cattle.io/owner-namespace: fleet-local
      rancher.io/service-account.secret-ref: fleet-local/custom-86920bbe7f61-machine-bootstrap-token-cz26s
    creationTimestamp: "2026-06-12T10:45:19Z"
    labels:
      objectset.rio.cattle.io/hash: 9672a50e031a9b69dec237022fe46287d08a9051
      rke.cattle.io/machine-name: custom-86920bbe7f61
      rke.cattle.io/rkebootstrap-name: custom-86920bbe7f61
      rke.cattle.io/service-account-role: bootstrap
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
            f:rancher.io/service-account.secret-ref: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
            f:rke.cattle.io/machine-name: {}
            f:rke.cattle.io/rkebootstrap-name: {}
            f:rke.cattle.io/service-account-role: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4d0b3b91-d07a-42cc-a311-ff8fe04cccb0"}: {}
      manager: rancher
      operation: Update
      time: "2026-06-12T10:45:19Z"
    name: custom-86920bbe7f61-machine-bootstrap
    namespace: fleet-local
    ownerReferences:
    - apiVersion: rke.cattle.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: RKEBootstrap
      name: custom-86920bbe7f61
      uid: 4d0b3b91-d07a-42cc-a311-ff8fe04cccb0
    resourceVersion: "8826"
    uid: 736919e5-8fac-4f7a-a6f4-68c046c1019e
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5SSQY/TQAyF/wryOVMmaTdpInFBcNoD0h64IA4ex6FDpuNqxi2HKv8dJWgRCzTqHpPx9/xsvyscWbFHReiugDGKonqJef4U951JM+smedkQqgbeeHnre+ggjWyciGZNeILiZrH8iJzMt8v4i/nj5VIWbx597N89PX58f7dSxCNDB3TOKkezr9vKOsfNUJd3ofmENPNDYFYThDDAVEBAx2F16APmA3TQ1k2FD5bttsTW1W3PVG0bW1UD7+pq3/R2j619mM28nPaIdPCR1/2/RE4Bo8lMiXUFM8/Kc/k/Gmnk31d6Te/M6eKJDRLJOapJEmZ06TEVcL+dW0svYDnKEw+cOBJn6L5cAU/+M6fsJf4nLlCAC0Ljpxn8wIF1qdN05gJIoiYJgdPzn9HHOah/pWt1B+cl2rveuq1rS9PbBs2uIjK4LUszDPuB7Y6InIXp6zT9DAAA//87hge5PgMAAA
      objectset.rio.cattle.io/id: rke-bootstrap
      objectset.rio.cattle.io/owner-gvk: rke.cattle.io/v1, Kind=RKEBootstrap
      objectset.rio.cattle.io/owner-name: custom-86920bbe7f61
      objectset.rio.cattle.io/owner-namespace: fleet-local
      rancher.io/service-account.secret-ref: fleet-local/custom-86920bbe7f61-machine-plan-token-w5knq
    creationTimestamp: "2026-06-12T10:45:19Z"
    labels:
      objectset.rio.cattle.io/hash: 9672a50e031a9b69dec237022fe46287d08a9051
      rke.cattle.io/machine-name: custom-86920bbe7f61
      rke.cattle.io/plan-secret-name: custom-86920bbe7f61-machine-plan
      rke.cattle.io/rkebootstrap-name: custom-86920bbe7f61
      rke.cattle.io/service-account-role: plan
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
            f:rancher.io/service-account.secret-ref: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
            f:rke.cattle.io/machine-name: {}
            f:rke.cattle.io/plan-secret-name: {}
            f:rke.cattle.io/rkebootstrap-name: {}
            f:rke.cattle.io/service-account-role: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4d0b3b91-d07a-42cc-a311-ff8fe04cccb0"}: {}
      manager: rancher
      operation: Update
      time: "2026-06-12T10:45:19Z"
    name: custom-86920bbe7f61-machine-plan
    namespace: fleet-local
    ownerReferences:
    - apiVersion: rke.cattle.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: RKEBootstrap
      name: custom-86920bbe7f61
      uid: 4d0b3b91-d07a-42cc-a311-ff8fe04cccb0
    resourceVersion: "8815"
    uid: f69ba4f5-b180-47dd-96a3-a63a1f1e5fd3
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2026-06-12T10:39:48Z"
    name: default
    namespace: fleet-local
    resourceVersion: "1220"
    uid: 6eeaa2d9-dacd-4927-864e-df6926f6c246
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yNsW6EMBAF/2XrmCCIwfA3z+slODE2wpsK8e8RuuquuHKk0cxJmygCFDSfhJyLQmPJ9cbif4S1ijZHLA1DNUkTy2cMNNPxK53ZwGvMYrjkJX4bToL8t9P1QQle0tvKirrSTCFMwfMSRu6dczb0rYwO7AcL68ROQzd8ta7t7mjGJi/r57OpoIdWd/DtLklETSqMRNf1HwAA//8UxgqC7wAAAA
      objectset.rio.cattle.io/id: rke2-machine-config-cleanup
    creationTimestamp: "2026-06-12T10:42:20Z"
    labels:
      objectset.rio.cattle.io/hash: dd9dbcfd7c38885d30e78acb65a58e5962640802
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
      manager: rancher
      operation: Update
      time: "2026-06-12T10:42:20Z"
    name: rke2-machineconfig-cleanup-sa
    namespace: fleet-local
    resourceVersion: "3737"
    uid: e5999b68-fb8e-4bf0-9770-f1eb2103d6c0
kind: List
metadata:
  resourceVersion: "676422"
