apiVersion: v1
items:
- apiVersion: node.harvesterhci.io/v1beta1
  kind: NodeConfig
  metadata:
    annotations:
      AppliedConfig: '{"ntpServers":"0.suse.pool.ntp.org 1.suse.pool.ntp.org"}'
    creationTimestamp: "2026-06-12T10:44:04Z"
    finalizers:
    - wrangler.cattle.io/harvester-node-config-controller
    generation: 1
    managedFields:
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:longhornConfig: {}
          f:ntpConfigs:
            .: {}
            f:ntpServers: {}
      manager: harvester
      operation: Update
      time: "2026-06-12T10:44:04Z"
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:AppliedConfig: {}
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/harvester-node-config-controller"null: {}
      manager: harvester-node-manager
      operation: Update
      time: "2026-06-12T10:44:04Z"
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:ntpConditions: {}
      manager: harvester-node-manager
      operation: Update
      subresource: status
      time: "2026-06-12T10:44:04Z"
    name: hp-117-tink-system
    namespace: harvester-system
    resourceVersion: "7279"
    uid: 7b92f6e8-3316-49ca-95c3-735b165382d6
  spec:
    longhornConfig: {}
    ntpConfigs:
      ntpServers: 0.suse.pool.ntp.org 1.suse.pool.ntp.org
  status:
    ntpConditions:
    - lastProbeTime: "null"
      lastTransitionTime: "null"
      message: NTP config is created or modified, need to wait it to be applied
      reason: NTPConfigModified
      status: "False"
      type: Modified
    - lastProbeTime: "null"
      lastTransitionTime: "null"
      message: NTP config is Applied
      reason: NTPConfigApplied
      status: "True"
      type: Applied
- apiVersion: node.harvesterhci.io/v1beta1
  kind: NodeConfig
  metadata:
    annotations:
      AppliedConfig: '{"ntpServers":"0.suse.pool.ntp.org 1.suse.pool.ntp.org"}'
    creationTimestamp: "2026-06-12T10:47:11Z"
    finalizers:
    - wrangler.cattle.io/harvester-node-config-controller
    generation: 1
    managedFields:
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:longhornConfig: {}
          f:ntpConfigs:
            .: {}
            f:ntpServers: {}
      manager: harvester
      operation: Update
      time: "2026-06-12T10:47:11Z"
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:AppliedConfig: {}
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/harvester-node-config-controller"null: {}
      manager: harvester-node-manager
      operation: Update
      time: "2026-06-12T10:47:34Z"
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:ntpConditions: {}
      manager: harvester-node-manager
      operation: Update
      subresource: status
      time: "2026-06-12T10:47:34Z"
    name: hp-150-tink-system
    namespace: harvester-system
    resourceVersion: "11815"
    uid: 4655f1a1-b135-414c-996e-351c92fcbb67
  spec:
    longhornConfig: {}
    ntpConfigs:
      ntpServers: 0.suse.pool.ntp.org 1.suse.pool.ntp.org
  status:
    ntpConditions:
    - lastProbeTime: "null"
      lastTransitionTime: "null"
      message: NTP config is created or modified, need to wait it to be applied
      reason: NTPConfigModified
      status: "False"
      type: Modified
    - lastProbeTime: "null"
      lastTransitionTime: "null"
      message: NTP config is Applied
      reason: NTPConfigApplied
      status: "True"
      type: Applied
- apiVersion: node.harvesterhci.io/v1beta1
  kind: NodeConfig
  metadata:
    annotations:
      AppliedConfig: '{"ntpServers":"0.suse.pool.ntp.org 1.suse.pool.ntp.org"}'
    creationTimestamp: "2026-06-12T10:47:12Z"
    finalizers:
    - wrangler.cattle.io/harvester-node-config-controller
    generation: 1
    managedFields:
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:longhornConfig: {}
          f:ntpConfigs:
            .: {}
            f:ntpServers: {}
      manager: harvester
      operation: Update
      time: "2026-06-12T10:47:12Z"
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:AppliedConfig: {}
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/harvester-node-config-controller"null: {}
      manager: harvester-node-manager
      operation: Update
      time: "2026-06-12T10:47:43Z"
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:ntpConditions: {}
      manager: harvester-node-manager
      operation: Update
      subresource: status
      time: "2026-06-12T10:47:43Z"
    name: hp-69-tink-system
    namespace: harvester-system
    resourceVersion: "12178"
    uid: 60f6c67d-da98-46f3-8e92-d76e12f523ab
  spec:
    longhornConfig: {}
    ntpConfigs:
      ntpServers: 0.suse.pool.ntp.org 1.suse.pool.ntp.org
  status:
    ntpConditions:
    - lastProbeTime: "null"
      lastTransitionTime: "null"
      message: NTP config is created or modified, need to wait it to be applied
      reason: NTPConfigModified
      status: "False"
      type: Modified
    - lastProbeTime: "null"
      lastTransitionTime: "null"
      message: NTP config is Applied
      reason: NTPConfigApplied
      status: "True"
      type: Applied
kind: List
metadata:
  continue: "null"
  resourceVersion: "676449"
